### ISSUE TITLE
Proposal for entity list system (Trac #2567)

### ISSUE THREAD

**Issue by elgg-gitbot** [Elgg/Elgg#2567]
_Original ticket http://trac.elgg.org/ticket/2567 on 40796290-01-22 by trac user mrclay, assigned to trac user mrclay._

I've [http://mrclay.org/index.php/2010/10/17/elgg-core-proposal-new-table-entity_list_items/ posted a proposal] to add an "entity list" system (and at least one new table) in the core. This would greatly ease the creation of features like this:[[BR]]
[[BR]]
- A “featured items” widget for a group or user. On a group page this could be implemented in left/right lists for more display control[[BR]]
- “Sticky” entities in discussion lists, or any other object lists[[BR]]
- A “favorites” list for each user

Working API plugin using relationships for storage: https://github.com/mrclay/Elgg-elggx_lists_api but I suggest the relationship schema move to [lists](https://docs.google.com/a/elgg.org/document/d/1R3v_bYno6fw8mV5_GDW93uTI0pvR9S4yQ-BHMKTz1zs/edit).
### TODOs
- [ ] Agree on a set of interfaces
- [ ] Agree on a set of expected behaviors (tests)
- [ ] Compile a list of use cases
- [ ] Document usage pattern for these use cases
### Interfaces for discussion

Open questions:
- Naming conventions

``` php
interface Entity {
  // properties
  function getGuid();

  // graph traversal
  function lists(): Map<string, EntityList>;
}

interface Relationship {
  // properties
  function getIndex(): int;
  function setIndex($index);
  function getTimeCreated(): DateTimeImmutable;
  function getWeight(): number;
  function setWeight($weight);

  // graph traversal
  function parent(): Entity;
  function child(): Entity;
}

interface EntityList extends Map<Entity, Relationship>, MutableSequence<Relationship> {
  // properties
  function getName(): string;

  // graph traversal
  function parent(): Entity;
  function children(): MutableSeries<Entity>;
}

interface MutableCollection<Y> extends Collection<T> {
  function add(T $item): void;
  function remove(T $item): void;
}

interface Sequence<T> extends Collection<T> {
  function getAt($index): T;
  function indexOf(T $item): int;
  function slice($startingAtThisIndex = 0, $returnThisNumberOfItems = 0): Series<T>;
}

interface MutableSequence<T> extends Sequence<T>, MutableCollection<T> {
  function insertAt($index, T $item): void;
  function removeAt($index): T;
  function splice($startingAtThisIndex = 0, $removeThisNumberOfItems = 0, T ...$andInsertTheseInTheirPlace): Series<T>;
}

interface Map<K, V> extends Collection<V> {
  function get(K $key): V;
}

interface MutableMap<K, V> extends Map<K, V> {
  function set(K $key, V $value): void;
}
```

There `where` method is probably the most mysterious (and difficult to implement). My idea here was to allow something like elgg_get_entities, but with a slightly cleaned up API:

``` php
// All items in the List with a weight of exactly 1.0
$list->where(['weight' => 1.0]);

// All items in the List with a weight between 1.0 and 2.0
$list->where([
  'weight' => [
    '>' => 1.0,
    '<' => 2.0,
  ]
]);
```

I find it a little clearer than the QueryModifier concept, which is too vague (modify how, exactly?).

**Comment by mrclay** [comment]
I eventually arrived at this API: https://github.com/mrclay/Elgg-elggx_lists_api
There's nothing stopping us from basing this on the current relationship schema, but I propose we at least normalize names. Ideally we'd migrate to this ["lists" schema](https://docs.google.com/a/elgg.org/document/d/1R3v_bYno6fw8mV5_GDW93uTI0pvR9S4yQ-BHMKTz1zs/edit) (ignore the bit about ACLs).

**Comment by mrclay** [comment]
Still missing: view to re-order items. The action is done, based on jQuery UI sortable, but I haven't made a dedicated view for it. Challenge being dealing with very long lists.

Also, current API doesn't fire relationship events. I'm not sure what would be ideal here, as re-ordering items involves removing and re-adding relationships... it's kind of it's own thing.

**Comment by jdalsem** [comment]
Weights on relationships? #4462

**Comment by mrclay** [comment]
In my plugin lists are ordered by relationship.id, so in the lists schema I suggest we just call this column "position"

**Comment by mrclay** [comment]
but yes, essentially lists have an order, but if you're using the schema as relationships, you just ignore order

**Comment by ewinslow** [comment]
API seems nice. I'd even encourage more OO, instead of the `*_get_list` API you have documented there now. E.g.:

```php
$members = $group->getList('members')
if (!$members->contains($user)) {
  $members->add($user);
}
```

The main question I would have is how to expose metadata about the relationships (relationship time_created, weight -- if we were to add it -- etc.?)

**Comment by propertunist** [comment]
just so you know, i already created a plugin that adds sort functionality to lists and it is running on my site. it would be great to get a core function for that.

**Comment by propertunist** [comment]
just a reminder that this is now the ticket that covers the introduction of a generic 'featured items' function, since the original ticket was closed in favor of this one.

**Comment by mrclay** [comment]
If you want a featured items feature, reopen that ticket, but this is for adding the API that (hopefully) will power it.

**Comment by propertunist** [comment]
99% of tickets i create get support and are then closed. in this case, the ticket was closed due to it being moved to another ticket. when i viewed that ticket, it too had been closed and moved to this ticket.

**Comment by mrclay** [comment]
I'm sorry? Maybe a community discussion on ticket etiquette would be useful?

**Comment by propertunist** [comment]
i think so, yes. there appears to be intent to just close as many as possible, without communicating between all involved

**Comment by ewinslow** [comment]
@propertunist Feel free to contest or request justification. Closing tickets without justification is poor form.

**Comment by propertunist** [comment]
you can follow the thread from the original ticket here: https://github.com/Elgg/Elgg/issues/6293
if i contest the issue on the original closed ticket, will anyone read my comment?

**Comment by hypeJunction** [comment]
Yes, we receive a notification for every comment made here.

**Comment by ewinslow** [comment]
@mrclay I think a practical next step here would be to write up the interfaces that would be exposed. That gives us a reference from which to work, rather than relying on examples alone which always leaves me thinking "is the whole API covered by this set of examples?"

**Comment by mrclay** [comment]
Lists can't have IDs until we migrate to the new schema.

Rather than starting from scratch again, could we just try to build something on [my implementation](https://github.com/mrclay/Elgg-elggx_lists_api) and find what it's missing, etc. I've put a ton of time into it finding the simplest boundaries I could find to get it work.

**Comment by mrclay** [comment]
Since we're staying on the relationships schema it worth noting that my implementation doesn't fire relationship events. To provide generic actions that could be reused by plugins I do however have a simple embedded permission system (based of elgg_can) to determine who can add/remove/rearrange items. This can be simplified however we see fit.

**Comment by ewinslow** [comment]
Good observation about not being able to get lists by ID.

We don't have to start the implementation from scratch, but I would like the opportunity to discuss the interface.

**Comment by ewinslow** [comment]
I put some more time into defining the interfaces necessary for this. It's missing several APIs compared to @mrclay implementation but I believe it doesn't lose any expressiveness and the methods are more "standard", based on my knowledge of collection/list APIs.

**Comment by jdalsem** [comment]
The usecases mentioned in the original post can easily be achieved by `elgg_list_entities`. For runtime list manipulation we currently have `Elgg\Collections`. For now i think this is enough. There is however a need for more persistent lists (that removes the need for complex queries), but that is somethings else.
