### ISSUE TITLE
CI and automation

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7354]
Collecting some CI-related tasks and automation wishes into a to-do list:

* [ ] Explode long commit messages - #7344 
* [x] Remove trailing white spaces - discussion #7350 
* [ ] Fix spacing after type casting - disucssion #6542

**Comment by hypeJunction** [comment]
This just duplicates other tickets.
