### ISSUE TITLE
Add an admin area page for security diagnostics/hardening

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#7537]
I created a plugin https://github.com/ColdTrick/security_tools and released it on the community https://community.elgg.org/plugins/1941178.

@ewinslow [requested](https://community.elgg.org/plugins/1941178/releases/2.0) that i start a discussion issue to see what we can move to core, 

so go ;)

settings to be added
- [x] notify all admins about admin add/remove
- [x] notify user about getting/removing admin role
- [x] notify user about (un)ban
- [x] notify user about password change
- [x] protect upgrade.php
- [x] protect cron urls
- [x] disable autocomplete on password fields

Info page
- [x] is site https
- [x] wwwroot is writeable
- [x] no hooks on filter_tags (could point to vulnerable get_input())
- [x] minimal password length
- [x] minimal username length
- [x] site secret strength (from advanced site settings)
- [x] php session gc settings
- [x] ~php version~ see #5627
- [x] ~mysql version~ see #5627
- [x] ~php open_basedir info~ see #12411

**Comment by ewinslow** [comment]
Should check for whether HTTPS is enabled/possible.

**Comment by jdalsem** [comment]
all requested information has been added to admin pages
